"""generic_job_tracking

Revision ID: 2e51b9150fbd
Revises: a39f45620fe7
Create Date: 2026-02-27 13:20:02.424679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2e51b9150fbd'
down_revision: Union[str, Sequence[str], None] = 'a39f45620fe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_service_email_blasts',
    sa.Column('id', mysql.INTEGER(), nullable=False),
    sa.Column('job_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('subject', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('body_html', mysql.TEXT(), nullable=False),
    sa.Column('body_text', mysql.TEXT(), nullable=True),
    sa.Column('is_templated', mysql.TINYINT(display_width=1), server_default='0', nullable=False),
    sa.Column('delivery_status', sa.Enum('pending', 'sent', 'partial', 'failed', name='emailblastdeliverystatus'), server_default='pending', nullable=False),
    sa.Column('sent_count', mysql.INTEGER(), server_default='0', nullable=False),
    sa.Column('failed_count', mysql.INTEGER(), server_default='0', nullable=False),
    sa.Column('failed_recipients', sa.JSON(), nullable=True),
    sa.Column('provider_response', sa.JSON(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['email_service_jobs.id'], name='email_service_email_blasts_job_fk', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('email_service_email_blasts_job_id', 'email_service_email_blasts', ['job_id'], unique=True)
    op.add_column('email_service_jobs', sa.Column('job_config', sa.JSON(), nullable=True))
    op.alter_column('email_service_jobs', 'event_id',
               existing_type=mysql.INTEGER(unsigned=True),
               nullable=True)
    op.add_column('email_service_recipients', sa.Column('email', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('email_service_recipients', sa.Column('name', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('email_service_recipients', sa.Column('custom_data', sa.JSON(), nullable=True))
    op.alter_column('email_service_recipients', 'member_id',
               existing_type=mysql.INTEGER(unsigned=True),
               nullable=True)
    op.drop_index(op.f('email_service_recipients_unique'), table_name='email_service_recipients')
    op.create_index('email_service_recipients_email', 'email_service_recipients', ['email'], unique=False)
    op.drop_constraint(op.f('email_service_recipients_member_fk'), 'email_service_recipients', type_='foreignkey')
    op.create_foreign_key('email_service_recipients_member_fk', 'email_service_recipients', 'members', ['member_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('email_service_recipients_member_fk', 'email_service_recipients', type_='foreignkey')
    op.create_foreign_key(op.f('email_service_recipients_member_fk'), 'email_service_recipients', 'members', ['member_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_index('email_service_recipients_email', table_name='email_service_recipients')
    op.create_index(op.f('email_service_recipients_unique'), 'email_service_recipients', ['job_id', 'member_id'], unique=True)
    op.alter_column('email_service_recipients', 'member_id',
               existing_type=mysql.INTEGER(unsigned=True),
               nullable=False)
    op.drop_column('email_service_recipients', 'custom_data')
    op.drop_column('email_service_recipients', 'name')
    op.drop_column('email_service_recipients', 'email')
    op.alter_column('email_service_jobs', 'event_id',
               existing_type=mysql.INTEGER(unsigned=True),
               nullable=False)
    op.drop_column('email_service_jobs', 'job_config')
    op.drop_index('email_service_email_blasts_job_id', table_name='email_service_email_blasts')
    op.drop_table('email_service_email_blasts')
    # ### end Alembic commands ###
