"""add_email_service_tables

Revision ID: a39f45620fe7
Revises:
Create Date: 2026-02-27 09:34:02.250739

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "a39f45620fe7"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_service_jobs",
        sa.Column("id", mysql.VARCHAR(length=36), nullable=False),
        sa.Column("event_id", mysql.INTEGER(unsigned=True), nullable=False),
        sa.Column(
            "job_type",
            sa.Enum(
                "certificate",
                "reminder",
                "notification",
                "custom",
                name="emailservicejobtype",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "processing",
                "completed",
                "failed",
                name="emailservicejobstatus",
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("total", mysql.INTEGER(), server_default="0", nullable=False),
        sa.Column("completed", mysql.INTEGER(), server_default="0", nullable=False),
        sa.Column("successful", mysql.INTEGER(), server_default="0", nullable=False),
        sa.Column("failed", mysql.INTEGER(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "email_service_jobs_event_id", "email_service_jobs", ["event_id"], unique=False
    )
    op.create_table(
        "email_service_recipients",
        sa.Column("id", mysql.INTEGER(), nullable=False),
        sa.Column("job_id", mysql.VARCHAR(length=36), nullable=False),
        sa.Column("member_id", mysql.INTEGER(unsigned=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "sent", "failed", name="emailservicerecipientstatus"),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("sent_at", sa.DateTime(), nullable=True),
        sa.Column("error", mysql.TEXT(), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["email_service_jobs.id"],
            name="email_service_recipients_job_fk",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
            name="email_service_recipients_member_fk",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "email_service_recipients_job_id",
        "email_service_recipients",
        ["job_id"],
        unique=False,
    )
    op.create_index(
        "email_service_recipients_member_id",
        "email_service_recipients",
        ["member_id"],
        unique=False,
    )
    op.create_index(
        "email_service_recipients_unique",
        "email_service_recipients",
        ["job_id", "member_id"],
        unique=True,
    )
    op.create_table(
        "email_service_certificates",
        sa.Column("id", mysql.INTEGER(), nullable=False),
        sa.Column("recipient_id", mysql.INTEGER(), nullable=False),
        sa.Column("certificate_path", mysql.VARCHAR(length=500), nullable=False),
        sa.Column(
            "template_type",
            sa.Enum("official", "unofficial", name="emailservicetemplatetype"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["recipient_id"],
            ["email_service_recipients.id"],
            name="email_service_certificates_recipient_fk",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "email_service_certificates_recipient_id",
        "email_service_certificates",
        ["recipient_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "email_service_certificates_recipient_id",
        table_name="email_service_certificates",
    )
    op.drop_table("email_service_certificates")
    op.drop_index(
        "email_service_recipients_unique", table_name="email_service_recipients"
    )
    op.drop_index(
        "email_service_recipients_member_id", table_name="email_service_recipients"
    )
    op.drop_index(
        "email_service_recipients_job_id", table_name="email_service_recipients"
    )
    op.drop_table("email_service_recipients")
    op.drop_index("email_service_jobs_event_id", table_name="email_service_jobs")
    op.drop_table("email_service_jobs")
    # ### end Alembic commands ###
